version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
  build:
    commands:
      - echo "Building the TypeScript backend..."
      - npm run build
artifacts:
  files:
    - '**/*'
